'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { Clock3, FileText, Mail, MapPin, MessageCircle, Phone, ShieldCheck, Ticket } from 'lucide-react'
import { billingContact, contactInfo, footerGroups, rightsLinks, socialLinks, whatsappLink } from '@/lib/iplux-links'

function Logo() { return <Link href="/" className="flex items-center" aria-label="IPLUX inicio"><Image src="/images/iplux-logo.png" alt="IPLUX 100% Fibra Óptica" width={158} height={48} className="h-12 w-auto brightness-0 invert object-contain" /></Link> }

export function FooterColumn({ title, links }: { title: string; links: string[][] }) { const [open, setOpen] = useState(false); return <section className="border-b border-white/10 py-4 md:border-0 md:py-0"><button onClick={() => setOpen(!open)} className="flex w-full items-center justify-between text-left font-bold text-white md:pointer-events-none" aria-expanded={open}><span>{title}</span><span className="text-xl text-cyan-300 md:hidden">{open ? '−' : '+'}</span></button><div className={`${open ? 'mt-4 grid' : 'hidden'} gap-3 md:mt-5 md:grid`}>{links.map(([label, href]) => href.startsWith('/') ? <Link key={label} href={href} className="text-sm text-blue-200 transition hover:text-cyan-300">{label}</Link> : <a key={label} href={href} className="text-sm text-blue-200 transition hover:text-cyan-300">{label}</a>)}</div></section> }

export function SocialLinks() { const icons: Record<string, string> = { f: '/images/social/facebook.png', ig: '/images/social/instagram.png', yt: '/images/social/youtube.png', tk: '/images/social/tiktok.png' }; return <div className="flex gap-2">{socialLinks.map(({ label, href, short }) => <a key={label} href={href} target="_blank" rel="noreferrer" aria-label={label} className="grid h-9 w-9 place-items-center rounded-lg border border-white/20 transition hover:border-cyan-300"><Image src={icons[short]} alt={label} width={16} height={16} className="h-4 w-4 object-contain" /></a>)}</div> }

export function ContactInfo() { return <div className="space-y-3 text-sm text-blue-100"><a href={`tel:${contactInfo.phone.replaceAll(' ', '')}`} className="flex items-start gap-3 hover:text-cyan-300"><Phone size={17} className="mt-0.5 text-cyan-300" />{contactInfo.phone}</a><a href={whatsappLink('Hola IPLUX, quisiera información sobre sus planes y cobertura.')} target="_blank" rel="noreferrer" className="flex items-start gap-3 hover:text-cyan-300"><MessageCircle size={17} className="mt-0.5 text-cyan-300" />WhatsApp: {contactInfo.phone}</a><span className="flex items-start gap-3"><Mail size={17} className="mt-0.5 text-cyan-300" />{contactInfo.email}</span><span className="flex items-start gap-3"><Clock3 size={17} className="mt-0.5 text-cyan-300" />{contactInfo.hours}</span><span className="flex items-start gap-3"><MapPin size={17} className="mt-0.5 text-cyan-300" />{contactInfo.address}</span></div> }

export function ComplaintsBookButton() { return <Link href="/libro-de-reclamaciones" className="flex items-center gap-3 rounded-xl border border-cyan-300/40 bg-cyan-300/10 p-4 text-sm font-bold text-white transition hover:bg-cyan-300/20"><Ticket className="text-cyan-300" size={22} /><span><span className="block">Libro de Reclamaciones</span><span className="mt-1 block text-xs font-normal text-blue-200">Presenta tu reclamo o queja</span></span></Link> }

export function WhatsAppFloatingButton() { return <a href={whatsappLink('Hola IPLUX, quisiera información sobre sus planes y cobertura.')} target="_blank" rel="noreferrer" className="fixed bottom-5 right-5 z-40 flex h-14 items-center gap-2 rounded-full bg-[#17c964] px-4 font-bold text-white shadow-xl shadow-green-900/25 transition hover:scale-105" aria-label="Escríbenos por WhatsApp"><MessageCircle size={23} /><span className="hidden sm:inline">Escríbenos por WhatsApp</span></a> }

export function CallFloatingButton() { return <a href={`tel:${contactInfo.phone.replaceAll(' ', '')}`} className="fixed bottom-5 right-[18rem] z-40 hidden h-12 items-center gap-2 rounded-full bg-[#087ff0] px-4 text-sm font-bold text-white shadow-xl shadow-blue-900/20 transition hover:scale-105 lg:flex"><Phone size={18} /> Llámanos</a> }

export function IpluxFooter() { return <footer id="footer" className="bg-[#071a35] text-white"><div className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-[1.15fr_1fr_1fr_1fr_1.15fr]"><div><Logo /><p className="mt-4 text-sm font-bold text-cyan-300">100% Fibra Óptica</p><p className="mt-3 max-w-xs text-sm leading-6 text-blue-200">Conectamos hogares con Internet de alta velocidad, entretenimiento y atención personalizada.</p><div className="mt-5"><SocialLinks /></div></div>{footerGroups.map((group) => <FooterColumn key={group.title} title={group.title} links={group.links} />)}<div><h2 className="font-bold">Medios de pago</h2><div className="mt-4 space-y-2 text-sm text-blue-200"><p>Yape y Plin: solicita los datos actualizados</p><a href={`https://wa.me/${billingContact.whatsapp}?text=${encodeURIComponent('Hola IPLUX, quisiera solicitar los datos bancarios para realizar el pago de mi servicio.')}`} target="_blank" rel="noreferrer" className="block hover:text-cyan-300">Transferencia bancaria: solicitar datos</a><Link href="/medios-de-pago" className="inline-block pt-1 font-bold text-cyan-300 hover:text-white">Ver medios de pago</Link></div><h2 className="mt-8 font-bold">Contacto</h2><div className="mt-5"><ContactInfo /></div><div className="mt-5"><ComplaintsBookButton /></div></div></div><div className="mt-10 border-t border-white/10 pt-8"><div className="grid gap-4 lg:grid-cols-2"><div><h2 className="mb-4 flex items-center gap-2 font-bold"><ShieldCheck className="text-cyan-300" size={18} />Tus derechos</h2><div className="flex flex-wrap gap-x-5 gap-y-2">{rightsLinks.map((link) => <Link key={link} href="/informacion-usuarios" className="text-xs text-blue-200 hover:text-cyan-300">{link}</Link>)}</div></div><Link href="/informacion-usuarios" className="flex items-center gap-3 rounded-xl border border-white/10 p-4 text-sm text-blue-100 hover:border-cyan-300/50"><FileText className="text-cyan-300" size={20} />Centro de información para abonados y usuarios</a></div></div></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-5 py-5 text-xs text-blue-300 md:flex-row md:items-center md:justify-between lg:px-8"><span>© IPLUX. Todos los derechos reservados.</span><div className="flex flex-wrap gap-4"><a href="/informacion-usuarios">Términos y condiciones</a><a href="/informacion-usuarios">Política de privacidad</a><a href="/informacion-usuarios">Política de cookies</a></div><span className="font-bold text-cyan-300">100% Fibra Óptica</span></div></div><WhatsAppFloatingButton /><CallFloatingButton /></footer> }
