import { ArrowLeft, Building2, Check, MessageCircle, Smartphone } from 'lucide-react'
import { paymentWhatsappLink } from '@/lib/payment-methods'
import { SiteHeader } from '@/components/layout/iplux-header'

const paymentCards = [
  { name: 'Yape', detail: 'Solicita el número actualizado por WhatsApp.', tone: 'bg-[#7424a8]', logo: '/images/payments/yape.png' },
  { name: 'Plin', detail: 'Solicita el número actualizado por WhatsApp.', tone: 'bg-[#0d9b83]', logo: '/images/payments/plin.png' },
  { name: 'Transferencia bancaria', detail: 'Los datos bancarios se proporcionan únicamente mediante nuestros canales oficiales de atención.', tone: 'bg-[#0873d1]', logo: null },
]

const paymentMessage = 'Hola IPLUX, quisiera solicitar los datos actualizados para realizar el pago de mi servicio.'

export default function PaymentMethodsPage() {
  return <main className="min-h-screen bg-[#f4faff] text-[#092a62] dark:bg-[#08111f] dark:text-slate-50"><SiteHeader /><section className="mx-auto max-w-6xl px-5 py-10 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#079f9a] dark:text-[#63d6d3]">Opciones oficiales</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Paga tu servicio de forma fácil</h1><p className="mt-4 text-lg leading-8 text-slate-600 dark:text-slate-300">IPLUX cuenta con opciones de pago mediante Yape, Plin y transferencia bancaria. Los datos de pago pueden variar según la zona o atención correspondiente. Solicita la información actualizada mediante nuestros canales oficiales de WhatsApp.</p></div><div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950 dark:border-amber-800/60 dark:bg-amber-950/30 dark:text-amber-100"><strong>Importante:</strong> Antes de realizar cualquier pago, verifica siempre el número y nombre del receptor indicado por nuestro equipo.</div><div className="mt-10 grid gap-5 lg:grid-cols-3">{paymentCards.map((card) => <article key={card.name} className="rounded-3xl border border-blue-100 bg-white p-6 shadow-sm dark:border-[#2b4058] dark:bg-[#13243a]"><div className={`grid h-14 w-14 place-items-center rounded-2xl text-2xl font-black text-white ${card.tone}`}>{card.logo ? <img src={card.logo} alt={`Logo ${card.name}`} className="h-9 w-9 object-contain" /> : <Building2 size={27} />}</div><h2 className="mt-6 text-2xl font-black text-[#092a62] dark:text-slate-50">{card.name}</h2><div className="mt-5 rounded-2xl bg-[#f1f8ff] p-4 text-sm leading-6 text-slate-600 dark:bg-[#10294b] dark:text-slate-300"><p>{card.detail}</p><div className="mt-4 flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-[#0873d1] dark:text-[#60a5fa]"><Check size={16} /> Datos entregados por canal oficial</div></div></article>)}</div><div className="mt-10 rounded-3xl border border-blue-100 bg-white p-7 shadow-sm dark:border-[#2b4058] dark:bg-[#13243a]"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[#e5fbfb] text-[#0873d1] dark:bg-[#16364a] dark:text-[#63d6d3]"><MessageCircle size={22} /></span><div><h2 className="text-2xl font-black text-[#092a62] dark:text-slate-50">Solicita tus datos de pago</h2><p className="mt-2 max-w-2xl leading-7 text-slate-600 dark:text-slate-300">No asumimos un único número de Yape o Plin: la información puede variar según Lima, Huancayo, sede o zona de atención. Por ahora, solicítala directamente a nuestro equipo.</p><a href={paymentWhatsappLink(paymentMessage)} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#0873d1] px-5 py-3 font-bold text-white transition hover:bg-[#0664b7]"><Smartphone size={18} /> Solicitar datos de pago por WhatsApp</a></div></div></div></section></main>
}
