import { ArrowRight, CreditCard, FileText, HelpCircle, LockKeyhole, ShieldCheck, Ticket } from 'lucide-react'
import { SiteHeader } from '@/components/layout/iplux-header'

const cards = [
  { icon: Ticket, title: 'Reclamos', text: 'Conoce cómo presentar una solicitud o reclamo ante IPLUX.', href: '/libro-de-reclamaciones' },
  { icon: FileText, title: 'Condiciones de servicio', text: 'Consulta los documentos oficiales de Internet y TV cuando estén publicados.', href: '#legal' },
  { icon: CreditCard, title: 'Medios de pago', text: 'Información sobre las alternativas de pago disponibles para abonados.', href: '#pagos' },
  { icon: LockKeyhole, title: 'Protección de datos', text: 'Conoce cómo protegemos y tratamos tus datos personales.', href: '#legal' },
  { icon: ShieldCheck, title: 'Derechos del usuario', text: 'Accede a información clara sobre tus derechos como usuario.', href: '#derechos' },
  { icon: HelpCircle, title: 'Preguntas frecuentes', text: 'Respuestas a las consultas más comunes sobre nuestros servicios.', href: '/#preguntas' },
  { icon: Ticket, title: 'Libro de Reclamaciones', text: 'Presenta un reclamo o queja mediante nuestro formulario.', href: '/libro-de-reclamaciones' },
]

export default function InformacionUsuariosPage() { return <main className="min-h-screen bg-[#eef8ff] text-[#10265c] dark:bg-[#08111f] dark:text-slate-50"><SiteHeader /><section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#078d98] dark:text-[#63d6d3]">Centro institucional</p><h1 className="mt-3 max-w-3xl text-4xl font-black sm:text-5xl">Información para abonados y usuarios</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">Encuentra orientación sobre tus servicios, derechos, pagos, reclamos y documentos de IPLUX. Los contenidos legales definitivos serán incorporados por IPLUX.</p><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{cards.map(({ icon: Icon, title, text, href }) => <article key={title} className="flex flex-col rounded-2xl border border-blue-100 bg-white p-6 shadow-sm dark:border-[#2b4058] dark:bg-[#13243a]"><div className="grid h-12 w-12 place-items-center rounded-xl bg-[#e5fbfb] text-[#0873d1] dark:bg-[#16364a] dark:text-[#63d6d3]"><Icon size={23} /></div><h2 className="mt-5 text-xl font-extrabold text-[#10265c] dark:text-slate-50">{title}</h2><p className="mt-2 flex-1 text-sm leading-6 text-slate-500 dark:text-slate-300">{text}</p><a href={href} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#087ff0] dark:text-[#60a5fa]">Ver información <ArrowRight size={16} /></a></article>)}</div><div id="legal" className="mt-12 rounded-2xl border border-cyan-100 bg-white p-6 text-sm leading-7 text-slate-600 dark:border-[#2b4058] dark:bg-[#13243a] dark:text-slate-300"><h2 className="text-xl font-extrabold text-[#10265c] dark:text-slate-50">Documentos oficiales</h2><p className="mt-2">Esta sección está preparada para publicar las condiciones de servicio, términos, políticas y documentos oficiales de IPLUX. No constituye todavía el texto legal definitivo.</p></div></section></main> }
